/**
 * Created by ling xue on 15-9-8.
 */

/**
 * Image Type
 */
var IMAGE_TYPE_BRAND = 1 ;
var IMAGE_TYPE_AUTO = 2;

/**
 * ADMIN USER STATUS
 */
var ADMIN_USER_STATUS_ACTIVE = 1 ;
var ADMIN_USER_STATUS_NOT_ACTIVE = 0;

/**
 * USER STATUS
 */
var USER_STATUS_ACTIVE = 1 ;
var USER_STATUS_NOT_ACTIVE = 0;

/**
 * User Type
 */
var USER_TYPE_SUPPLIER = 1;
/**
 * AUTO STATUS
 */
var AUTO_STATUS_ACTIVE = 1 ;
var AUTO_STATUS_NOT_ACTIVE = 0;

/**
 * PROCURE STATUS
 */
var PROCURE_STATUS_ACTIVE = 1 ;
var PROCURE_STATUS_OVER =2;

/**
 * OFFER STATUS
 */
var OFFER_STATUS_NORMAL = 1;
var OFFER_STATUS_SELECTED =2;

var QUEUE_MSG_TYPE_EMAIL = 1;
var QUEUE_MSG_TYPE_SMS = 2;
module.exports = {
    USER_STATUS_ACTIVE : USER_STATUS_ACTIVE ,
    USER_STATUS_NOT_ACTIVE : USER_STATUS_NOT_ACTIVE ,
    ADMIN_USER_STATUS_ACTIVE : ADMIN_USER_STATUS_ACTIVE ,
    ADMIN_USER_STATUS_NOT_ACTIVE : ADMIN_USER_STATUS_NOT_ACTIVE ,
    IMAGE_TYPE_BRAND : IMAGE_TYPE_BRAND ,
    IMAGE_TYPE_AUTO : IMAGE_TYPE_AUTO ,
    AUTO_STATUS_ACTIVE : AUTO_STATUS_ACTIVE ,
    AUTO_STATUS_NOT_ACTIVE : AUTO_STATUS_NOT_ACTIVE ,
    USER_STATUS_ACTIVE : USER_STATUS_ACTIVE ,
    USER_STATUS_NOT_ACTIVE : USER_STATUS_NOT_ACTIVE ,
    USER_TYPE_SUPPLIER : USER_TYPE_SUPPLIER ,
    PROCURE_STATUS_ACTIVE  : PROCURE_STATUS_ACTIVE ,
    PROCURE_STATUS_OVER : PROCURE_STATUS_OVER ,
    OFFER_STATUS_NORMAL : OFFER_STATUS_NORMAL ,
    OFFER_STATUS_SELECTED : OFFER_STATUS_SELECTED ,
    QUEUE_MSG_TYPE_EMAIL : QUEUE_MSG_TYPE_EMAIL ,
    QUEUE_MSG_TYPE_SMS : QUEUE_MSG_TYPE_SMS
}