

/**
 * ADMIN USER STATUS
 */
var ADMIN_USER_STATUS_ACTIVE = 1 ;
var ADMIN_USER_STATUS_NOT_ACTIVE = 0;

/**
 * USER STATUS
 */
var USER_STATUS_ACTIVE = 1 ;
var USER_STATUS_NOT_ACTIVE = 0;

/**
 * CAR STATUS
 */
var CAR_STATUS_OUT = 9;
var CAR_STATUS_MOVE = 1;

/**
 * CarStorageRel STATUS
 */
var REL_STATUS_OUT = 2 ;
var REL_STATUS_MOVE = 1;

/**
 * RelActive STATUS
 */
var REL_STATUS_ACTIVE = 1 ;
var REL_STATUS_NOT_ACTIVE = 0;

/**
 * CONTACTS STATUS
 */
var CONTACTS_STATUS_ACTIVE = 1 ;
var CONTACTS_STATUS_NOT_ACTIVE = 0;

module.exports = {
    USER_STATUS_ACTIVE : USER_STATUS_ACTIVE ,
    USER_STATUS_NOT_ACTIVE : USER_STATUS_NOT_ACTIVE ,
    ADMIN_USER_STATUS_ACTIVE : ADMIN_USER_STATUS_ACTIVE ,
    ADMIN_USER_STATUS_NOT_ACTIVE : ADMIN_USER_STATUS_NOT_ACTIVE,
    CAR_STATUS_OUT : CAR_STATUS_OUT,
    CAR_STATUS_MOVE : CAR_STATUS_MOVE,
    REL_STATUS_OUT : REL_STATUS_OUT,
    REL_STATUS_MOVE : REL_STATUS_MOVE,
    REL_STATUS_ACTIVE : REL_STATUS_ACTIVE,
    REL_STATUS_NOT_ACTIVE : REL_STATUS_NOT_ACTIVE,
    CONTACTS_STATUS_ACTIVE : CONTACTS_STATUS_ACTIVE,
    CONTACTS_STATUS_NOT_ACTIVE : CONTACTS_STATUS_NOT_ACTIVE
}