

/**
 * ADMIN USER STATUS
 */
var ADMIN_USER_STATUS_ACTIVE = 1 ;
var ADMIN_USER_STATUS_NOT_ACTIVE = 0;

/**
 * USER STATUS
 */
var USER_STATUS_ACTIVE = 1 ;
var USER_STATUS_NOT_ACTIVE = 0;

module.exports = {
    USER_STATUS_ACTIVE : USER_STATUS_ACTIVE ,
    USER_STATUS_NOT_ACTIVE : USER_STATUS_NOT_ACTIVE ,
    ADMIN_USER_STATUS_ACTIVE : ADMIN_USER_STATUS_ACTIVE ,
    ADMIN_USER_STATUS_NOT_ACTIVE : ADMIN_USER_STATUS_NOT_ACTIVE
}